[package]
name = "SuperDev-Practice"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = "1.0.219"
tokio = { version = "1.45.1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] }
solana-client = "1.18"
solana-sdk = "1.18"
